// Generates sidebars.ts (the "Course" sidebar) from the grader's manifest.
//
// The course is grouped by TAOCP *volume*, not by module number, so the sidebar
// cannot be autogenerated from the filesystem. This reads the same JSON the
// grader emits (`./grade manifest`) — the single source of truth — so the site
// navigation can never drift from the curriculum. Run via `npm run gen`.
import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname, resolve} from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(
  readFileSync(resolve(here, '../src/data/manifest.json'), 'utf8'),
);

// The four Markdown files every module folder carries, in reading order.
// README is the module's landing doc; the rest are nested beneath it.
const PARTS = [
  ['WALKTHROUGH', 'Walkthrough'],
  ['exercises', 'Exercises'],
  ['hints', 'Hints'],
];

const volumeLabel = (v) =>
  `${v.key.replace('Vol.', 'Volume')} · ${v.name}`;

const categories = manifest.volumes.map((v) => ({
  type: 'category',
  label: volumeLabel(v),
  collapsed: true,
  collapsible: true,
  items: v.modules.map((m) => ({
    type: 'category',
    label: `${m.id} · ${m.title}`,
    collapsed: true,
    link: {type: 'doc', id: `${m.dir}/README`},
    items: PARTS.map(([file, label]) => ({
      type: 'doc',
      id: `${m.dir}/${file}`,
      label,
    })),
  })),
}));

const banner = `// AUTO-GENERATED by scripts/gen-sidebar.mjs from src/data/manifest.json.
// Do not edit by hand — run \`npm run gen\` after changing the grader manifest.
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
`;

const body = `\nconst sidebars: SidebarsConfig = {\n  course: ${JSON.stringify(
  categories,
  null,
  2,
)},\n};\n\nexport default sidebars;\n`;

writeFileSync(resolve(here, '../sidebars.ts'), banner + body);
console.log(
  `sidebars.ts: ${manifest.volumes.length} volumes, ` +
    `${manifest.volumes.reduce((n, v) => n + v.modules.length, 0)} modules`,
);
