//! Module 12 — The Spectral Test.
//! Source: TAOCP Vol. 2, 3rd ed., §3.3.4.
//!
//! Overlapping t-tuples of a linear congruential sequence x_{n+1} = a·x_n
//! mod m lie on a lattice; the spectral test measures the coarsest family
//! of parallel hyperplanes covering that lattice. The key quantity is
//!
//! ```text
//! nu_t^2 = min { u1^2 + ... + ut^2 :
//!                u1 + a·u2 + ... + a^{t-1}·ut ≡ 0 (mod m), u ≠ 0 },
//! ```
//!
//! the squared length of the shortest nonzero vector of the *dual* lattice.
//! The maximum distance between adjacent covering hyperplanes is m/nu_t, so
//! small nu_t = bad generator. All arithmetic is exact in `i128`; moduli up
//! to about 2^31 are supported (norms then fit comfortably: m^2 < 2^62).
//!
//! Note on the increment c: for x_{n+1} = (a·x_n + c) mod m the point set of
//! t-tuples is the c = 0 point set *translated* by a constant vector, so the
//! lattice structure — and everything computed here — is independent of c.
//! We therefore work with the multiplicative form throughout.

/// Overlapping t-tuples of the sequence x_{n+1} = a·x_n mod m.
///
/// Returns `count` tuples: (x_0,...,x_{t-1}), (x_1,...,x_t), ...,
/// (x_{count-1},...,x_{count+t-2}), starting from seed `x0`.
///
/// TAOCP Vol. 2, §3.3.4, preliminaries: these points, taken over a full
/// period, are exactly the lattice generated by (1, a, a^2, ..., a^{t-1})
/// and m·e_2, ..., m·e_t, intersected with the cube [0, m)^t — because the
/// tuple starting at x_n is x_n·(1, a, ..., a^{t-1}) reduced mod m in each
/// coordinate.
pub fn tuples(a: i64, m: i64, t: usize, x0: i64, count: usize) -> Vec<Vec<i64>> {
    assert!(m >= 2, "modulus m must be at least 2");
    assert!(0 < a && a < m, "multiplier must satisfy 0 < a < m");
    assert!(t >= 1, "tuple dimension t must be at least 1");
    assert!(0 <= x0 && x0 < m, "seed must satisfy 0 <= x0 < m");
    let (a, m128) = (a as i128, m as i128);
    // Generate count + t - 1 terms, then slide a window of width t over them.
    let n = count + t - 1;
    let mut xs: Vec<i64> = Vec::with_capacity(n);
    let mut x = x0 as i128;
    for _ in 0..n {
        xs.push(x as i64);
        x = a * x % m128;
    }
    (0..count).map(|i| xs[i..i + t].to_vec()).collect()
}

/// Is `u` a nonzero vector of the dual lattice of the t-tuple lattice?
///
/// Checks the congruence  u1 + a·u2 + a^2·u3 + ... + a^{t-1}·ut ≡ 0 (mod m)
/// with t = u.len(), and that u ≠ 0. Every t-tuple x of the sequence then
/// satisfies u·x ≡ 0 (mod m), i.e. x lies on one of the hyperplanes
/// u·x = k·m — that is the sense in which u is "dual" to the point set.
pub fn is_dual_vector(u: &[i64], a: i64, m: i64) -> bool {
    assert!(m >= 2, "modulus m must be at least 2");
    assert!(0 < a && a < m, "multiplier must satisfy 0 < a < m");
    assert!(!u.is_empty(), "dual vector must have at least one coordinate");
    if u.iter().all(|&ui| ui == 0) {
        return false; // u = 0 satisfies the congruence trivially; excluded.
    }
    let (a, m) = (a as i128, m as i128);
    let mut pow = 1i128; // a^{i} mod m, i = 0, 1, ..., t-1
    let mut s = 0i128; // partial sum of u_{i+1} · a^i, reduced mod m
    for &ui in u {
        // |ui % m| < m and pow < m, so the product fits easily in i128.
        s = (s + (ui as i128 % m) * pow).rem_euclid(m);
        pow = pow * a % m;
    }
    s == 0
}

/// Round-to-nearest integer division d/n for n > 0 (ties go up).
/// floor((2d + n) / (2n)) is the nearest integer to d/n.
fn div_round(d: i128, n: i128) -> i128 {
    debug_assert!(n > 0);
    (2 * d + n).div_euclid(2 * n)
}

/// The exact two-dimensional spectral test: nu_2^2 for x_{n+1} = a·x_n mod m.
///
/// The dual lattice in two dimensions is
///     L* = { (u1, u2) : u1 + a·u2 ≡ 0 (mod m) },
/// with basis v1 = (m, 0), v2 = (-a, 1): every u2 is realised by v2·u2, and
/// u1 is then determined mod m, which v1 accounts for. nu_2^2 is the squared
/// length of the shortest nonzero vector of L*, found by Gauss–Lagrange
/// reduction — the two-dimensional ancestor of LLL, and essentially Euclid's
/// algorithm on vectors:
///
/// ```text
/// G1. [Initialize.] v1 <- (m, 0), v2 <- (-a, 1).
/// G2. [Order.]      If |v1| < |v2|, interchange v1 and v2.
/// G3. [Reduce.]     Let q be the nearest integer to (v1·v2)/(v2·v2);
///                   set v1 <- v1 - q·v2.
/// G4. [Done?]       If |v1| >= |v2|, terminate; v2 is a shortest nonzero
///                   vector of the lattice. Otherwise return to G2.
/// ```
///
/// Termination: each pass through G3 that does not terminate strictly
/// decreases min(|v1|, |v2|), and squared norms are positive integers.
/// Optimality: on exit |v1| >= |v2| and |v1·v2| <= (v2·v2)/2 (property of
/// the rounded quotient), whence for any integers (α, β) ≠ (0, 0):
/// |α·v1 + β·v2|^2 >= (α^2 - |αβ| + β^2)·|v2|^2 >= |v2|^2.
pub fn nu2_squared(a: i64, m: i64) -> i128 {
    assert!(m >= 2, "modulus m must be at least 2");
    assert!(0 < a && a < m, "multiplier must satisfy 0 < a < m");
    // G1. [Initialize.]
    let mut v1 = (m as i128, 0i128);
    let mut v2 = (-(a as i128), 1i128);
    loop {
        // G2. [Order.] Make v1 the longer vector.
        let n1 = v1.0 * v1.0 + v1.1 * v1.1;
        let n2 = v2.0 * v2.0 + v2.1 * v2.1;
        if n1 < n2 {
            std::mem::swap(&mut v1, &mut v2);
        }
        let n2 = n1.min(n2);
        // G3. [Reduce.] Subtract the nearest-integer multiple of v2 from v1.
        let q = div_round(v1.0 * v2.0 + v1.1 * v2.1, n2);
        v1 = (v1.0 - q * v2.0, v1.1 - q * v2.1);
        // G4. [Done?]
        if v1.0 * v1.0 + v1.1 * v1.1 >= n2 {
            return n2;
        }
    }
}

/// The exact three-dimensional spectral test, with a certified bounded
/// search: nu_3^2 for x_{n+1} = a·x_n mod m.
///
/// Dual vectors in three dimensions satisfy
///     u1 + a·u2 + a^2·u3 ≡ 0 (mod m),
/// so (u2, u3) may be chosen freely and u1 is then determined modulo m; the
/// shortest choice of u1 in its residue class is the *centered* residue of
/// -(a·u2 + a^2·u3) mod m, with |u1| <= m/2 (any other member of the class
/// differs by a nonzero multiple of m and is at least as large in absolute
/// value, so it can never yield a shorter vector).
///
/// Search: scan (u2, u3) ∈ [-B, B]^2 with the centered u1, keeping the best
/// squared norm seen; start from best = m^2, realised by (m, 0, 0), the
/// shortest nonzero member of the class (u2, u3) = (0, 0). Double B until
/// B^2 >= best.
///
/// Certification: when B^2 >= best, any dual vector u with |u2| > B or
/// |u3| > B satisfies |u|^2 >= u2^2 + u3^2 > B^2 >= best, so it cannot beat
/// the minimum found; and every class with |u2|, |u3| <= B was scanned with
/// its optimal u1. Hence best = nu_3^2 exactly.
///
/// Termination bound: by Hermite's theorem with γ_3 = 2^{1/3}, the dual
/// lattice (determinant m) has nu_3^2 <= 2^{1/3}·m^{2/3}; for m <= 2^31 this
/// is < 2.2·10^6 < (2^11.5)^2, so B never exceeds 4096 and the whole search
/// stays within a few tens of millions of cheap iterations.
pub fn nu3_squared_certified(a: i64, m: i64) -> i128 {
    assert!(m >= 2, "modulus m must be at least 2");
    assert!(0 < a && a < m, "multiplier must satisfy 0 < a < m");
    let m = m as i128;
    let a1 = a as i128; // a   mod m
    let a2 = a1 * a1 % m; // a^2 mod m
    // Class (u2, u3) = (0, 0): u1 ≡ 0 (mod m), shortest nonzero is (±m, 0, 0).
    let mut best = m * m;
    let mut b: i128 = 1;
    loop {
        for u3 in -b..=b {
            // r = (a·u2 + a^2·u3) mod m in [0, m), maintained incrementally
            // as u2 runs from -b to b (adding a1 each step, reducing once).
            let mut r = (a2 * u3 + a1 * (-b)).rem_euclid(m);
            for u2 in -b..=b {
                if u2 != 0 || u3 != 0 {
                    // Centered residue: u1 ≡ -r (mod m) with |u1| <= m/2.
                    let u1 = if 2 * r > m { m - r } else { -r };
                    let norm = u1 * u1 + u2 * u2 + u3 * u3;
                    if norm < best {
                        best = norm;
                    }
                }
                r += a1;
                if r >= m {
                    r -= m;
                }
            }
        }
        // Certified once B^2 >= best: any vector outside the square is longer.
        if b * b >= best {
            return best;
        }
        b *= 2;
    }
}

/// Figure of merit μ_2 = π·nu_2^2 / m  (TAOCP Vol. 2, §3.3.4, Eq. (37)).
///
/// μ_t is the volume of the t-ball of radius nu_t divided by the determinant
/// m of the dual lattice — the "expected number" of dual lattice points in a
/// ball whose radius is the shortest-vector length. Values well below 0.1
/// flag a bad multiplier; values around 1 or above are excellent. Hermite's
/// bound nu_2^2 <= (2/√3)·m caps μ_2 at 2π/√3 ≈ 3.63.
pub fn mu2(a: i64, m: i64) -> f64 {
    let nu2sq = nu2_squared(a, m);
    std::f64::consts::PI * nu2sq as f64 / m as f64
}

/// Figure of merit μ_3 = (4/3)·π·nu_3^3 / m  (same source, t = 3;
/// π^{3/2}/(3/2)! = 4π/3). nu_3 is the square root of the exact nu_3^2,
/// taken in f64. Hermite's bound nu_3^2 <= 2^{1/3}·m^{2/3} caps μ_3 at
/// (4π/3)·√2 ≈ 5.92.
pub fn mu3(a: i64, m: i64) -> f64 {
    let nu3sq = nu3_squared_certified(a, m);
    let nu3 = (nu3sq as f64).sqrt();
    4.0 / 3.0 * std::f64::consts::PI * nu3.powi(3) / m as f64
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Brute-force nu_2^2 justified by Hermite's theorem: the dual lattice
    /// has determinant m, so nu_2^2 <= γ_2·m = (2/√3)·m. Any dual vector
    /// with |u2| > sqrt((2/√3)·m) is already longer than that bound, so
    /// scanning u2 in [1, B] (u and -u have equal length; u2 = 0 gives the
    /// class of (m, 0)) with the centered u1 residue is exhaustive.
    fn nu2_squared_brute(a: i64, m: i64) -> i128 {
        let (a, m) = (a as i128, m as i128);
        let bound = (2.0 / 3.0f64.sqrt()) * m as f64;
        let b = bound.sqrt().ceil() as i128;
        let mut best = m * m; // class u2 = 0: shortest nonzero is (m, 0)
        for u2 in 1..=b {
            let r = (a * u2).rem_euclid(m); // u1 ≡ -r (mod m)
            let u1 = if 2 * r > m { m - r } else { -r };
            best = best.min(u1 * u1 + u2 * u2);
        }
        best
    }

    /// Full brute-force nu_3^2 for tiny m: every residue class (u2, u3) in
    /// [-m, m]^2 with the centered u1 (classes repeat mod m, so this range
    /// covers them all, and larger |u2|, |u3| only lengthen the vector
    /// because nu_3^2 <= m^2 always, witnessed by (m, 0, 0)).
    fn nu3_squared_brute_tiny(a: i64, m: i64) -> i128 {
        let (a, m) = (a as i128, m as i128);
        let a2 = a * a % m;
        let mut best = m * m;
        for u3 in -m..=m {
            for u2 in -m..=m {
                if u2 == 0 && u3 == 0 {
                    continue;
                }
                let r = (a * u2 + a2 * u3).rem_euclid(m);
                let u1 = if 2 * r > m { m - r } else { -r };
                best = best.min(u1 * u1 + u2 * u2 + u3 * u3);
            }
        }
        best
    }

    #[test]
    fn randu_dual_relation() {
        // §3.3.4: RANDU (a = 65539 = 2^16 + 3, m = 2^31, c = 0). Since
        // a^2 = 2^32 + 6·2^16 + 9 ≡ 6a - 9 (mod 2^31), every triple obeys
        // 9x_n - 6x_{n+1} + x_{n+2} ≡ 0 (mod 2^31): u = (9, -6, 1) is dual.
        let (a, m) = (65539i64, 1i64 << 31);
        assert!(is_dual_vector(&[9, -6, 1], a, m));
        for tup in tuples(a, m, 3, 1, 2000) {
            let s = 9 * tup[0] as i128 - 6 * tup[1] as i128 + tup[2] as i128;
            assert_eq!(s.rem_euclid(m as i128), 0);
        }
        // ... and (9, -6, 1) is in fact the SHORTEST dual vector:
        assert_eq!(nu3_squared_certified(a, m), 118); // 9^2 + 6^2 + 1^2
    }

    #[test]
    fn tuples_overlap_and_follow_the_recurrence() {
        // First terms of x_{n+1} = 137·x_n mod 256 from x_0 = 1:
        // 1, 137, 81, 87, ... (137^2 = 18769 = 73·256 + 81).
        let ts = tuples(137, 256, 2, 1, 5);
        assert_eq!(ts.len(), 5);
        for w in &ts {
            assert_eq!(w[1], w[0] * 137 % 256);
        }
        // Overlap: second coordinate of tuple i = first coordinate of i+1.
        for i in 0..ts.len() - 1 {
            assert_eq!(ts[i][1], ts[i + 1][0]);
        }
    }

    #[test]
    fn gauss_lagrange_hand_trace() {
        // The lesson hand-traces a = 137, m = 256:
        //   v1 = (256, 0), v2 = (-137, 1)
        //   q = -2 -> v1 = (-18, 2)   (norm 328  < 18770: continue)
        //   q =  8 -> v1 = (7, -15)   (norm 274  < 328:   continue)
        //   q = -1 -> v1 = (-11, -13) (norm 290 >= 274:   stop)
        // Shortest vector (7, -15), nu_2^2 = 274. Check: 7 - 137·15? No —
        // the dual relation is u1 + a·u2 ≡ 0: -7 + 137·15 = 2048 = 8·256. ✓
        assert_eq!(nu2_squared(137, 256), 274);
        assert!(is_dual_vector(&[-7, 15], 137, 256));
        assert!(is_dual_vector(&[-11, -13], 137, 256));
        // Second derivation: exhaustive search under the Hermite bound.
        assert_eq!(nu2_squared_brute(137, 256), 274);
    }

    #[test]
    fn reduction_matches_brute_force_everywhere_small() {
        for m in 2..=64i64 {
            for a in 1..m {
                assert_eq!(
                    nu2_squared(a, m),
                    nu2_squared_brute(a, m),
                    "nu2^2 mismatch at a={a}, m={m}"
                );
            }
        }
    }

    #[test]
    fn certified_3d_matches_brute_force_tiny() {
        for m in 2..=32i64 {
            for a in 1..m {
                assert_eq!(
                    nu3_squared_certified(a, m),
                    nu3_squared_brute_tiny(a, m),
                    "nu3^2 mismatch at a={a}, m={m}"
                );
            }
        }
    }

    #[test]
    fn minimal_standard_values() {
        // Lewis–Goodman–Miller "minimal standard": a = 16807, m = 2^31 - 1.
        // Computed by this module and frozen here (the stage tests reuse
        // these constants; if this test fails, the stage constants drift).
        let (a, m) = (16807i64, (1i64 << 31) - 1);
        // Shortest 2-D dual vector is (-16807, 1): a^2 < m keeps a·1 from
        // wrapping, so nothing shorter exists (checked by reduction).
        assert_eq!(nu2_squared(a, m), 16807i128 * 16807 + 1);
        // nu_3 ≈ 639: not RANDU-bad, but mediocre — Knuth's Table 1 rates
        // 16807 as "adequate, not outstanding", and this is why.
        assert_eq!(nu3_squared_certified(a, m), 408_197);
        // Figures of merit (frozen; the stage-4 bands derive from these):
        //   mu2 = pi·282475250/(2^31 - 1)      = 0.41323815...
        //   mu3 = (4/3)·pi·408197^{3/2}/(2^31-1) = 0.50870201...
        assert!((mu2(a, m) - 0.413_238_150_362_94).abs() < 1e-9);
        assert!((mu3(a, m) - 0.508_702_013_718_59).abs() < 1e-9);

        // Its modern replacement in the same family, a = 48271 (Park–Miller
        // revised): nu3^2 = 1_433_881, mu2 ≈ 2.912, mu3 ≈ 3.349 — an
        // excellent lattice for this m.
        assert_eq!(nu3_squared_certified(48271, m), 1_433_881);
        assert!((mu2(48271, m) - 2.912_282_728_59).abs() < 1e-9);
        assert!((mu3(48271, m) - 3.349_102_265_47).abs() < 1e-9);

        // Toy generator from the hand-trace: nu3^2 = 30 for (137, 256).
        assert_eq!(nu3_squared_certified(137, 256), 30);
    }

    #[test]
    fn randu_merit_is_catastrophic() {
        // nu_3^2 = 118 -> mu_3 = (4/3)π·118^{3/2}/2^31 ≈ 2.5e-6.
        let mu = mu3(65539, 1 << 31);
        assert!(mu < 1e-4, "RANDU mu3 = {mu}");
        assert!(mu > 1e-7);
    }

    #[test]
    fn non_dual_vectors_are_rejected() {
        assert!(!is_dual_vector(&[1, 0, 0], 65539, 1 << 31));
        assert!(!is_dual_vector(&[9, -6, 2], 65539, 1 << 31));
        assert!(!is_dual_vector(&[0, 0, 0], 65539, 1 << 31)); // zero vector
        assert!(!is_dual_vector(&[1, 1], 137, 256));
    }
}
