//! Module 16 — The Spectral Test in Higher Dimensions.
//! Source: TAOCP Vol. 2, 3rd ed., §3.3.4, Algorithm S.
//!
//! Module 12 computed nu_2 (Gauss–Lagrange reduction) and nu_3 (a certified
//! two-parameter scan). This module is the general machine for 2 <= t <= 6,
//! with the architecture of Knuth's Algorithm S: maintain a PAIR of bases,
//!
//! ```text
//! V: basis of the dual lattice
//!      L*_t = { u in Z^t : u1 + a·u2 + ... + a^{t-1}·ut ≡ 0 (mod m) },
//! U: basis of the m-scaled primal t-tuple lattice,
//! ```
//!
//! coupled by the exact identity U·Vᵀ = m·I, which every transformation
//! preserves (that identity is the correctness anchor of the whole module);
//! then SIZE-REDUCE V, mirroring each row operation on U so the identity
//! survives (cf. Knuth's transformation steps S5–S7); and finish with a
//! CERTIFIED ENUMERATION whose search box comes from Cramer's rule +
//! Cauchy–Schwarz (cf. Knuth's search steps S8–S10; his bound
//! z_k = floor(sqrt(floor(u_k·u_k·s/m^2))) is the same one computed here,
//! because the adjugate columns of V are ±(rows of U)).
//!
//! ```text
//! nu_t^2 = min { u1^2 + ... + ut^2 :
//!                u1 + a·u2 + ... + a^{t-1}·ut ≡ 0 (mod m), u ≠ 0 },
//! ```
//!
//! exactly as in module 12 (m12_spectral), and the figure of merit
//! mu_t = pi^{t/2}·nu_t^t / ((t/2)!·m) generalizes mu_2 and mu_3.
//!
//! All lattice arithmetic is exact in `i128`; moduli up to 2^31 are
//! supported. Bases are t×t `Vec<Vec<i128>>`, one basis vector per row.

/// Exact dot product of two rows.
fn dot(x: &[i128], y: &[i128]) -> i128 {
    debug_assert_eq!(x.len(), y.len());
    x.iter().zip(y).map(|(&a, &b)| a * b).sum()
}

/// Round-to-nearest integer division d/n for n > 0 (ties go up).
/// floor((2d + n) / (2n)) is the nearest integer to d/n — the same helper
/// module 12 used inside Gauss–Lagrange reduction.
fn div_round(d: i128, n: i128) -> i128 {
    debug_assert!(n > 0);
    (2 * d + n).div_euclid(2 * n)
}

/// Floor of the square root of n >= 0, exactly.
fn isqrt(n: i128) -> i128 {
    debug_assert!(n >= 0);
    if n < 2 {
        return n;
    }
    // Float seed, then exact fix-up (the float may be off by a few ulps).
    let mut x = (n as f64).sqrt() as i128;
    while x > 0 && x * x > n {
        x -= 1;
    }
    while (x + 1) * (x + 1) <= n {
        x += 1;
    }
    x
}

/// Exact determinant by Bareiss's fraction-free elimination with row
/// pivoting. Every division is exact (the divisor is the previous pivot, a
/// nonzero leading minor), so no rationals appear; intermediate entries are
/// k×k minors of the input, comfortably inside `i128` for the short reduced
/// bases this module feeds it.
fn determinant(mat: &[Vec<i128>]) -> i128 {
    let n = mat.len();
    if n == 0 {
        return 1; // det of the empty matrix (base case for 1×1 adjugates)
    }
    let mut m: Vec<Vec<i128>> = mat.to_vec();
    let mut sign = 1i128;
    let mut prev = 1i128;
    for k in 0..n - 1 {
        if m[k][k] == 0 {
            // Pivot: find a row below with a nonzero entry in column k.
            match (k + 1..n).find(|&r| m[r][k] != 0) {
                Some(p) => {
                    m.swap(k, p);
                    sign = -sign;
                }
                None => return 0, // column of zeros: singular
            }
        }
        for i in k + 1..n {
            for j in k + 1..n {
                // Bareiss step: the division by the previous pivot is exact.
                m[i][j] = (m[i][j] * m[k][k] - m[i][k] * m[k][j]) / prev;
            }
            m[i][k] = 0;
        }
        prev = m[k][k];
    }
    sign * m[n - 1][n - 1]
}

/// Column i of the adjugate adj(V): entry j is the cofactor
/// C_{ij} = (-1)^{i+j}·(minor of V with row i and column j deleted).
/// Cramer's rule in row form: if w = x·V then x_i = (w·g_i)/det V where
/// g_i is this column — the key to the certified search bound.
fn adjugate_column(v: &[Vec<i128>], i: usize) -> Vec<i128> {
    let t = v.len();
    (0..t)
        .map(|j| {
            let sub: Vec<Vec<i128>> = (0..t)
                .filter(|&r| r != i)
                .map(|r| (0..t).filter(|&c| c != j).map(|c| v[r][c]).collect())
                .collect();
            let sign = if (i + j) % 2 == 0 { 1 } else { -1 };
            sign * determinant(&sub)
        })
        .collect()
}

/// Stage 1 — the V-basis of the dual lattice in dimension t.
///
/// TAOCP Vol. 2, §3.3.4 (the setup of Algorithm S, cf. steps S1–S3): the
/// dual lattice L*_t = { u : u1 + a·u2 + ... + a^{t-1}·ut ≡ 0 (mod m) } is
/// generated by the rows
///
/// ```text
/// v_1 = (  m,               0, 0, ..., 0 )
/// v_2 = ( -(a     mod m),   1, 0, ..., 0 )
/// v_3 = ( -(a^2   mod m),   0, 1, ..., 0 )
///  ...
/// v_t = ( -(a^{t-1} mod m), 0, ..., 0, 1 )
/// ```
///
/// Each v_i satisfies the congruence (-a^{i-1} + a^{i-1}·1 ≡ 0); conversely
/// any dual u equals u_2·v_2 + ... + u_t·v_t + k·v_1 with the integer
/// k = (u_1 + Σ_{i>=2} u_i·(a^{i-1} mod m))/m, so the rows generate all of
/// L*_t. The matrix is lower triangular with diagonal (m, 1, ..., 1):
/// det V = m, the index of L*_t in Z^t.
///
/// Powers of a are kept reduced mod m, so no entry exceeds m in magnitude.
pub fn dual_basis(a: i64, m: i64, t: usize) -> Vec<Vec<i128>> {
    assert!(m >= 2, "modulus m must be at least 2");
    assert!(m <= 1 << 31, "moduli beyond 2^31 are not supported");
    assert!(0 < a && a < m, "multiplier must satisfy 0 < a < m");
    assert!(t >= 1, "dimension t must be at least 1");
    let (a, m) = (a as i128, m as i128);
    let mut v = vec![vec![0i128; t]; t];
    v[0][0] = m;
    let mut pow = 1i128; // a^{i-1} mod m
    for (i, row) in v.iter_mut().enumerate().skip(1) {
        pow = pow * a % m;
        row[0] = -pow;
        row[i] = 1;
    }
    v
}

/// Stage 1 — the U-basis of the m-scaled primal t-tuple lattice.
///
/// ```text
/// u_1 = ( 1, a mod m, a^2 mod m, ..., a^{t-1} mod m )
/// u_i = m·e_i                          for i = 2, ..., t
/// ```
///
/// u_1 is the generating tuple of module 12's lattice theorem (the t-tuple
/// starting at x = 1) and the m·e_i absorb the per-coordinate reductions.
/// The pair satisfies U·Vᵀ = m·I exactly — check against `dual_basis`:
/// u_1·v_1 = m; u_1·v_j = -(a^{j-1} mod m) + (a^{j-1} mod m)·1 = 0; and
/// u_i·v_j = m·(v_j)_i = m·δ_{ij} for i >= 2, because beyond the first
/// coordinate each v_j has a single nonzero entry, the 1 in position j.
/// This identity is the invariant every later transformation preserves.
pub fn primal_basis(a: i64, m: i64, t: usize) -> Vec<Vec<i128>> {
    assert!(m >= 2, "modulus m must be at least 2");
    assert!(m <= 1 << 31, "moduli beyond 2^31 are not supported");
    assert!(0 < a && a < m, "multiplier must satisfy 0 < a < m");
    assert!(t >= 1, "dimension t must be at least 1");
    let (a, m) = (a as i128, m as i128);
    let mut u = vec![vec![0i128; t]; t];
    let mut pow = 1i128;
    for j in 0..t {
        u[0][j] = pow; // a^j mod m
        pow = pow * a % m;
    }
    for (i, row) in u.iter_mut().enumerate().skip(1) {
        row[i] = m;
    }
    u
}

/// Stage 1 — does the pair (U, V) satisfy U·Vᵀ = m·I exactly?
///
/// Entry (i, j) of U·Vᵀ is the dot product u_i·v_j; the identity demands m
/// on the diagonal and 0 off it. Non-square or mismatched shapes are
/// rejected. This is the correctness anchor of the module: it certifies
/// that U and V still describe an exact dual pair of lattices after any
/// number of transformations.
pub fn check_duality(u: &[Vec<i128>], v: &[Vec<i128>], m: i64) -> bool {
    let t = u.len();
    if t == 0 || v.len() != t {
        return false;
    }
    if u.iter().chain(v.iter()).any(|row| row.len() != t) {
        return false;
    }
    let m = m as i128;
    for i in 0..t {
        for j in 0..t {
            let want = if i == j { m } else { 0 };
            if dot(&u[i], &v[j]) != want {
                return false;
            }
        }
    }
    true
}

/// Stage 2 — pairwise size reduction of V, mirrored on U.
///
/// TAOCP Vol. 2, §3.3.4, the transformation phase of Algorithm S (steps
/// S5–S7), restructured as a sweep-to-fixpoint:
///
/// ```text
/// R1. [Sweep.]     For each ordered pair (i, j) with i ≠ j, do R2–R3.
/// R2. [Quotient.]  d <- v_i·v_j, n <- v_j·v_j. If 2|d| <= n, the pair is
///                  already reduced; go on to the next pair.
/// R3. [Transform.] q <- round(d/n)  (nonzero, since |d/n| > 1/2);
///                  v_i <- v_i - q·v_j   and   u_j <- u_j + q·u_i.
/// R4. [Done?]      If a full sweep applied no transformation, stop.
///                  Otherwise start a new sweep at R1.
/// ```
///
/// Why the mirrored update keeps U·Vᵀ = m·I: the row operation on V is
/// V <- E·V with E = I - q·e_i e_jᵀ, and the one on U is U <- F·U with
/// F = I + q·e_j e_iᵀ; then F·Eᵀ = (I + q·e_j e_iᵀ)(I - q·e_j e_iᵀ) = I
/// (the two cross terms cancel and the q² term contains e_iᵀe_j = 0 since
/// i ≠ j), so U'·V'ᵀ = F·(U·Vᵀ)·Eᵀ = m·F·Eᵀ = m·I. Both E and F are
/// unimodular, so the lattices generated by the rows never change — only
/// the bases describing them do.
///
/// Termination: R3 fires only when 2|d| > n, and then the new squared norm
/// is |v_i|² + q·(q·n - 2d) < |v_i|², because q = round(d/n) with
/// |d/n| > 1/2 makes q ≠ 0 and q·n - 2d opposite in sign to q. So
/// Σ_i |v_i|², a positive integer, strictly decreases with every
/// transformation — the sweep loop halts.
///
/// At the fixpoint every pair satisfies 2|v_i·v_j| <= min(|v_i|², |v_j|²).
/// For t = 2 that is exactly the Gauss–Lagrange reduced condition, so the
/// shortest row realizes nu_2 (module 12's optimality proof applies
/// verbatim). For t >= 3 the shortest row need not be a shortest lattice
/// vector — that is what stage 3's certified enumeration is for — but the
/// rows become short enough to make the enumeration box tiny.
pub fn reduce_basis(v: &mut Vec<Vec<i128>>, u: &mut Vec<Vec<i128>>) {
    let t = v.len();
    assert_eq!(u.len(), t, "U and V must have the same number of rows");
    assert!(v.iter().all(|r| r.len() == t), "V must be square");
    assert!(u.iter().all(|r| r.len() == t), "U must be square");
    loop {
        // R1. [Sweep.]
        let mut changed = false;
        for j in 0..t {
            for i in 0..t {
                if i == j {
                    continue;
                }
                // R2. [Quotient.]
                let n = dot(&v[j], &v[j]);
                assert!(n > 0, "basis rows must be nonzero");
                let d = dot(&v[i], &v[j]);
                if 2 * d.abs() <= n {
                    continue;
                }
                // R3. [Transform.] v_i -= q·v_j paired with u_j += q·u_i.
                let q = div_round(d, n);
                for k in 0..t {
                    let s = q * v[j][k];
                    v[i][k] -= s;
                    let s = q * u[i][k];
                    u[j][k] += s;
                }
                changed = true;
            }
        }
        // R4. [Done?]
        if !changed {
            return;
        }
    }
}

/// Recursive box scan for `shortest_vector_squared`: coefficients
/// x_k ∈ [-z_k, z_k], with the partial sum Σ_{l<k} x_l·v_l maintained
/// incrementally, and the sign symmetry broken by forcing the first
/// nonzero coefficient to be positive (w and -w have equal norms, so this
/// halves the work and loses nothing).
fn scan_box(v: &[Vec<i128>], z: &[i128], k: usize, partial: &[i128], any: bool, best: &mut i128) {
    let t = v.len();
    if k == t {
        if any {
            let norm: i128 = partial.iter().map(|&c| c * c).sum();
            if norm < *best {
                *best = norm;
            }
        }
        return;
    }
    let lo = if any { -z[k] } else { 0 };
    let mut p: Vec<i128> = partial
        .iter()
        .zip(&v[k])
        .map(|(&pc, &vc)| pc + lo * vc)
        .collect();
    let mut x = lo;
    loop {
        scan_box(v, z, k + 1, &p, any || x != 0, best);
        if x == z[k] {
            break;
        }
        x += 1;
        for (pc, &vc) in p.iter_mut().zip(&v[k]) {
            *pc += vc;
        }
    }
}

/// Stage 3 — certified shortest-vector search on a (reduced) basis.
///
/// Returns min{ |x·V|² : x ∈ Z^t, x ≠ 0 } — the exact squared length of a
/// shortest nonzero vector of the lattice generated by the rows of `v` —
/// by enumeration over a finite box, cf. the search phase of Algorithm S
/// (steps S8–S10):
///
/// ```text
/// E1. [Seed.]    best <- min_i v_i·v_i  (attained by an actual row, so
///                the answer is at most this); d <- det V (Bareiss).
/// E2. [Bounds.]  For each i: g_i <- column i of adj(V), and
///                z_i <- floor(sqrt(best·|g_i|² / d²)).
/// E3. [Scan.]    For every x ≠ 0 with |x_i| <= z_i for all i:
///                best <- min(best, |x·V|²).
/// E4. [Return.]  best is certified; return it.
/// ```
///
/// THE CERTIFICATION ARGUMENT (why the box provably contains every
/// candidate). Let w = x·V be any nonzero lattice vector with |w|² <= best₀
/// (the seed value). Multiplying x·V = w on the right by adj(V) and using
/// V·adj(V) = (det V)·I gives Cramer's rule in row form,
/// x_i = (w·g_i)/det V, whence by Cauchy–Schwarz
///
/// ```text
/// |x_i|  <=  |w|·|g_i| / |det V|  <=  sqrt(best₀)·|g_i| / |d|,
/// ```
///
/// so |x_i| <= z_i (flooring is safe: x_i is an integer, and
/// floor(sqrt(N/D)) = floor(sqrt(floor(N/D))) for positive integers N, D).
/// Every lattice vector at least as short as the seed therefore has its
/// coefficient vector inside the scanned box; the scan sees it, and the
/// returned minimum is the true lattice minimum. No near-orthogonality
/// assumption enters — the bound is rigorous for ANY nonsingular basis.
/// Reduction (stage 2) merely makes the box SMALL: for this module's dual
/// pair, det V = ±m and the adjugate columns are ±(rows of U), so the z_i
/// are exactly the bounds Knuth derives in step S8 from the primal rows.
///
/// The zero vector is excluded by construction: the scan skips x = 0 and
/// the seed is a genuine row norm, so the result is always positive.
pub fn shortest_vector_squared(v: &[Vec<i128>]) -> i128 {
    let t = v.len();
    assert!(t >= 1, "basis must have at least one row");
    assert!(v.iter().all(|r| r.len() == t), "basis must be square");
    // E1. [Seed.]
    let d = determinant(v);
    assert!(d != 0, "basis rows must be linearly independent");
    let mut best = v.iter().map(|r| dot(r, r)).min().unwrap();
    // E2. [Bounds.]
    let z: Vec<i128> = (0..t)
        .map(|i| {
            let g = adjugate_column(v, i);
            isqrt(best * dot(&g, &g) / (d * d))
        })
        .collect();
    // E3. [Scan.]
    let partial = vec![0i128; t];
    scan_box(v, &z, 0, &partial, false, &mut best);
    // E4. [Return.]
    best
}

/// Stage 4 — the spectral test in dimension t, 2 <= t <= 6.
///
/// The full Algorithm S pipeline: build the dual pair (stage 1), size-
/// reduce it (stage 2), then run the certified enumeration on the reduced
/// V (stage 3). Returns
///
/// ```text
/// nu_t^2 = min { u1^2 + ... + ut^2 :
///                u1 + a·u2 + ... + a^{t-1}·ut ≡ 0 (mod m), u ≠ 0 },
/// ```
///
/// identical in meaning to module 12's nu2_squared and
/// nu3_squared_certified, now for every t up to 6. The maximum distance
/// between adjacent hyperplanes covering the t-tuple point set is m/nu_t.
pub fn nu_t_squared(a: i64, m: i64, t: usize) -> i128 {
    assert!((2..=6).contains(&t), "supported dimensions are 2 <= t <= 6");
    let mut v = dual_basis(a, m, t);
    let mut u = primal_basis(a, m, t);
    reduce_basis(&mut v, &mut u);
    debug_assert!(check_duality(&u, &v, m), "duality invariant violated");
    shortest_vector_squared(&v)
}

/// Stage 4 — Knuth's figure of merit μ_t (§3.3.4, Eq. (37)):
///
/// ```text
/// mu_t = pi^{t/2} · nu_t^t / ( Γ(t/2 + 1) · m ),
/// ```
///
/// the volume of the t-ball of radius nu_t divided by the determinant m of
/// the dual lattice. Γ(t/2 + 1) = (t/2)! is taken exactly for t <= 6:
///
/// ```text
/// Γ(2) = 1,  Γ(5/2) = 3√π/4,  Γ(3) = 2,  Γ(7/2) = 15√π/8,  Γ(4) = 6,
/// ```
///
/// so μ_2 = π·ν²/m and μ_3 = (4/3)π·ν³/m reproduce module 12, while
/// μ_4 = π²ν⁴/(2m), μ_5 = (8π²/15)ν⁵/m, μ_6 = π³ν⁶/(6m) extend them.
/// Rule of thumb (Knuth): μ_t >= 0.1 passes, μ_t >= 1 is excellent.
/// Floating point enters only here, after the integer minimum is frozen.
pub fn mu_t(a: i64, m: i64, t: usize) -> f64 {
    use std::f64::consts::PI;
    let nusq = nu_t_squared(a, m, t) as f64;
    let gamma = match t {
        2 => 1.0,               // Γ(2)   = 1! = 1
        3 => 0.75 * PI.sqrt(),  // Γ(5/2) = 3√π/4
        4 => 2.0,               // Γ(3)   = 2! = 2
        5 => 1.875 * PI.sqrt(), // Γ(7/2) = 15√π/8
        6 => 6.0,               // Γ(4)   = 3! = 6
        _ => unreachable!("nu_t_squared already rejected t outside 2..=6"),
    };
    let half_t = t as f64 / 2.0;
    PI.powf(half_t) * nusq.powf(half_t) / (gamma * m as f64)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Module 12's dual-vector predicate, re-implemented for cross-checks:
    /// u ≠ 0 and u1 + a·u2 + ... + a^{t-1}·ut ≡ 0 (mod m).
    fn is_dual_vector(u: &[i128], a: i64, m: i64) -> bool {
        if u.iter().all(|&ui| ui == 0) {
            return false;
        }
        let (a, m) = (a as i128, m as i128);
        let mut pow = 1i128;
        let mut s = 0i128;
        for &ui in u {
            s = (s + ui.rem_euclid(m) * pow).rem_euclid(m);
            pow = pow * a % m;
        }
        s == 0
    }

    /// Brute-force nu_t^2 for tiny m: scan the residue classes
    /// (u_2, ..., u_t) ∈ [-m, m]^{t-1} with the centered residue for u_1
    /// (module 12's argument: classes repeat mod m, nu_t^2 <= m^2 always,
    /// witnessed by (m, 0, ..., 0), and |u_1| <= m/2 is optimal per class).
    fn nu_t_squared_brute_tiny(a: i64, m: i64, t: usize) -> i128 {
        let (a, m) = (a as i128, m as i128);
        let mut pows = vec![1i128; t];
        for i in 1..t {
            pows[i] = pows[i - 1] * a % m;
        }
        let mut best = m * m;
        let mut tail = vec![-m; t - 1]; // (u_2, ..., u_t)
        loop {
            if tail.iter().any(|&x| x != 0) {
                let mut r = 0i128;
                for (i, &ui) in tail.iter().enumerate() {
                    r = (r + ui * pows[i + 1]).rem_euclid(m);
                }
                let u1 = if 2 * r > m { m - r } else { -r };
                let norm = u1 * u1 + tail.iter().map(|&x| x * x).sum::<i128>();
                best = best.min(norm);
            }
            // Odometer over [-m, m]^{t-1}.
            let mut k = 0;
            loop {
                if k == t - 1 {
                    return best;
                }
                if tail[k] == m {
                    tail[k] = -m;
                    k += 1;
                } else {
                    tail[k] += 1;
                    break;
                }
            }
        }
    }

    const RANDU_A: i64 = 65539;
    const RANDU_M: i64 = 1 << 31;
    const MM: i64 = (1 << 31) - 1; // 2^31 - 1, prime

    #[test]
    fn bases_have_the_documented_shape() {
        // Hand example a = 137, m = 256, t = 3: a² = 18769 ≡ 81 (mod 256).
        let v = dual_basis(137, 256, 3);
        assert_eq!(
            v,
            vec![vec![256, 0, 0], vec![-137, 1, 0], vec![-81, 0, 1]]
        );
        let u = primal_basis(137, 256, 3);
        assert_eq!(
            u,
            vec![vec![1, 137, 81], vec![0, 256, 0], vec![0, 0, 256]]
        );
        assert!(check_duality(&u, &v, 256));
        assert_eq!(determinant(&v), 256);
        assert_eq!(determinant(&u), 256i128 * 256);
    }

    #[test]
    fn duality_and_dual_rows_for_classic_generators() {
        for &(a, m) in &[(RANDU_A, RANDU_M), (16807, MM), (48271, MM), (137, 256)] {
            for t in 1..=6 {
                let u = primal_basis(a, m, t);
                let v = dual_basis(a, m, t);
                assert!(check_duality(&u, &v, m), "duality fails a={a} m={m} t={t}");
                for row in &v {
                    assert!(is_dual_vector(row, a, m), "non-dual row a={a} m={m} t={t}");
                }
            }
        }
    }

    #[test]
    fn check_duality_rejects_broken_pairs() {
        let u = primal_basis(137, 256, 4);
        let mut v = dual_basis(137, 256, 4);
        assert!(check_duality(&u, &v, 256));
        assert!(!check_duality(&u, &v, 255)); // wrong m
        v[2][0] += 1;
        assert!(!check_duality(&u, &v, 256)); // perturbed entry
        assert!(!check_duality(&u, &dual_basis(137, 256, 3), 256)); // shape mismatch
    }

    #[test]
    fn reduction_preserves_duality_and_shrinks_the_basis() {
        for &(a, m) in &[(RANDU_A, RANDU_M), (16807, MM), (48271, MM), (137, 256)] {
            for t in 2..=6 {
                let mut v = dual_basis(a, m, t);
                let mut u = primal_basis(a, m, t);
                let before: i128 = v.iter().map(|r| dot(r, r)).sum();
                reduce_basis(&mut v, &mut u);
                let after: i128 = v.iter().map(|r| dot(r, r)).sum();
                assert!(check_duality(&u, &v, m), "invariant lost a={a} m={m} t={t}");
                assert!(after <= before);
                for row in &v {
                    assert!(is_dual_vector(row, a, m), "reduced row left the lattice");
                }
                // Idempotence: a second reduction is a no-op.
                let (v2, u2) = (v.clone(), u.clone());
                reduce_basis(&mut v, &mut u);
                assert_eq!(v, v2);
                assert_eq!(u, u2);
            }
        }
    }

    #[test]
    fn randu_reduction_exposes_the_planes() {
        // The lesson hand-traces this: reducing V for RANDU at t = 3
        // collapses the basis onto the catastrophic dual vector (9, -6, 1)
        // (a² - 6a + 9 = 2^32 ≡ 0 mod 2^31). Reduction alone already finds
        // it as a shortest row.
        let mut v = dual_basis(RANDU_A, RANDU_M, 3);
        let mut u = primal_basis(RANDU_A, RANDU_M, 3);
        reduce_basis(&mut v, &mut u);
        let min_row = v.iter().map(|r| dot(r, r)).min().unwrap();
        assert_eq!(min_row, 118);
        assert!(v.iter().any(|r| r[..] == [9, -6, 1] || r[..] == [-9, 6, -1]));
    }

    #[test]
    fn t2_pipeline_matches_gauss_lagrange_brute_force() {
        // Module 12's Hermite-bounded 2-D brute force, re-implemented:
        // nu_2² <= (2/√3)·m, so scanning |u_2| <= sqrt((2/√3)·m) suffices.
        fn nu2_brute(a: i64, m: i64) -> i128 {
            let (a, m) = (a as i128, m as i128);
            let b = ((2.0 / 3.0f64.sqrt()) * m as f64).sqrt().ceil() as i128;
            let mut best = m * m;
            for u2 in 1..=b {
                let r = (a * u2).rem_euclid(m);
                let u1 = if 2 * r > m { m - r } else { -r };
                best = best.min(u1 * u1 + u2 * u2);
            }
            best
        }
        for m in 2..=64i64 {
            for a in 1..m {
                assert_eq!(nu_t_squared(a, m, 2), nu2_brute(a, m), "a={a} m={m}");
            }
        }
    }

    #[test]
    fn tiny_moduli_match_full_brute_force_up_to_t5() {
        for &m in &[9i64, 13, 16, 21] {
            for a in [2, 3, 5, 7, m - 1] {
                if a <= 0 || a >= m {
                    continue;
                }
                for t in 2..=5 {
                    assert_eq!(
                        nu_t_squared(a, m, t),
                        nu_t_squared_brute_tiny(a, m, t),
                        "nu_t² mismatch a={a} m={m} t={t}"
                    );
                }
            }
        }
    }

    #[test]
    fn module_12_pinned_values_reproduced() {
        // Frozen by module 12's reference (m12_spectral::tests):
        assert_eq!(nu_t_squared(RANDU_A, RANDU_M, 3), 118);
        assert_eq!(nu_t_squared(16807, MM, 2), 16807i128 * 16807 + 1);
        assert_eq!(nu_t_squared(16807, MM, 3), 408_197);
        assert_eq!(nu_t_squared(48271, MM, 3), 1_433_881);
        assert_eq!(nu_t_squared(137, 256, 2), 274);
        assert_eq!(nu_t_squared(137, 256, 3), 30);
        // And module 12's mu values, through the general Gamma formula:
        assert!((mu_t(16807, MM, 2) - 0.413_238_150_362_94).abs() < 1e-9);
        assert!((mu_t(16807, MM, 3) - 0.508_702_013_718_59).abs() < 1e-9);
        assert!((mu_t(48271, MM, 2) - 2.912_282_728_59).abs() < 1e-9);
        assert!((mu_t(48271, MM, 3) - 3.349_102_265_47).abs() < 1e-9);
    }

    #[test]
    fn higher_dimensional_values_frozen() {
        // Computed by this module and frozen here; the stage tests reuse
        // these constants (if this test fails, the stage constants drift).
        //
        // RANDU is catastrophic in EVERY dimension t >= 3: (9, -6, 1) padded
        // with zeros stays dual, so nu_t^2 <= 118 for all t >= 3 — and at
        // t = 4 something slightly shorter appears: (9, 3, -5, 1), i.e. the
        // polynomial (x - 3)²(x + 1) evaluated at a (norm 116).
        assert_eq!(nu_t_squared(RANDU_A, RANDU_M, 2), 2_147_221_514);
        assert_eq!(nu_t_squared(RANDU_A, RANDU_M, 4), 116);
        assert_eq!(nu_t_squared(RANDU_A, RANDU_M, 5), 116);
        assert_eq!(nu_t_squared(RANDU_A, RANDU_M, 6), 116);
        assert!(is_dual_vector(&[9, 3, -5, 1], RANDU_A, RANDU_M));
        // The minimal standard and its Park–Miller revision:
        assert_eq!(nu_t_squared(16807, MM, 4), 21_682);
        assert_eq!(nu_t_squared(16807, MM, 5), 4_439);
        assert_eq!(nu_t_squared(16807, MM, 6), 895);
        assert_eq!(nu_t_squared(48271, MM, 2), 1_990_735_345);
        assert_eq!(nu_t_squared(48271, MM, 4), 47_418);
        assert_eq!(nu_t_squared(48271, MM, 5), 4_404);
        assert_eq!(nu_t_squared(48271, MM, 6), 1_402);
        // The lesson's toy generator:
        assert_eq!(nu_t_squared(137, 256, 4), 14);
        assert_eq!(nu_t_squared(137, 256, 5), 6);
        assert_eq!(nu_t_squared(137, 256, 6), 4);
    }

    #[test]
    fn figures_of_merit_in_higher_dimensions() {
        // Knuth's rule of thumb: mu_t >= 0.1 passes, >= 1 excellent.
        // 48271 (Knuth's Table 1 lists it among the good multipliers, and
        // L'Ecuyer's tables keep it) is comfortably good at every t:
        for t in 2..=6 {
            assert!(mu_t(48271, MM, t) > 0.29, "48271 dips at t={t}");
        }
        // RANDU's merit collapses for every t >= 3 (the planes never heal;
        // the mu_t creep upward only because the ball volume normalization
        // weakens as t grows, while nu_t^2 stays frozen at ~116):
        assert!(mu_t(RANDU_A, RANDU_M, 3) < 1e-4);
        assert!(mu_t(RANDU_A, RANDU_M, 4) < 1e-3);
        assert!(mu_t(RANDU_A, RANDU_M, 5) < 1e-2);
        assert!(mu_t(RANDU_A, RANDU_M, 6) < 1e-1);
        // Cross-check mu_t against independently expanded closed forms
        // (this pins the exact half-integer Gamma values):
        use std::f64::consts::PI;
        let m = MM as f64;
        let nu4 = (nu_t_squared(48271, MM, 4) as f64).sqrt();
        assert!((mu_t(48271, MM, 4) - PI.powi(2) * nu4.powi(4) / (2.0 * m)).abs() < 1e-9);
        let nu5 = (nu_t_squared(48271, MM, 5) as f64).sqrt();
        assert!((mu_t(48271, MM, 5) - 8.0 * PI.powi(2) / 15.0 * nu5.powi(5) / m).abs() < 1e-9);
        let nu6 = (nu_t_squared(48271, MM, 6) as f64).sqrt();
        assert!((mu_t(48271, MM, 6) - PI.powi(3) * nu6.powi(6) / (6.0 * m)).abs() < 1e-9);
    }
}
